[workspace]
authors = ["Iason Krommydas <iason.krom@gmail.com>"]
channels = ["conda-forge"]
name = "2026-10-07-hsf-profiling-in-python"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
samply = "*"

[pypi-dependencies]
memray = "*"

[feature.py314.dependencies]
python = "3.14.*"
py-spy = "*"

[feature.py314.pypi-dependencies]
austin-dist = "*"
austin-python = "*"

[feature.py315]
channels = [{ channel = "conda-forge/label/python_rc", priority = 1 }]

[feature.py315.dependencies]
python = "3.15.*"

[environments]
default = ["py314"]
py315 = ["py315"]
